development: &default
  adapter: postgresql
  encoding: unicode
  database: childbrain_development
  pool: 5
  username: pollito
  password: pollito
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  adapter: postgresql
  database: childbrain_development
  pool: 5
  timeout: 5000

  production:
  adapter: postgresql
  database: childbrain_development
  pool: 5
  timeout: 5000
