development: &default
  adapter: postgresql
  encoding: unicode
  database: childbrai_development
  pool: 5
  username: pollito
  password: pollito
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  adapter: postgresql
  database: childbrai_development
  pool: 5
  timeout: 5000

  production:
  database: childbrai_development
  username: mp
  password: <%= ENV['MP_DATABASE_PASSWORD'] %>
